// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: movie_rating.proto
// Protobuf Java Version: 4.29.3

package com.julienviet.demos.movierating;

public final class MovieRatingOuterClass {
  private MovieRatingOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      MovieRatingOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_examples_grpc_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_examples_grpc_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_examples_grpc_MovieId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_examples_grpc_MovieId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_examples_grpc_MovieDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_examples_grpc_MovieDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_examples_grpc_MovieRating_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_examples_grpc_MovieRating_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_examples_grpc_MovieRatingDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_examples_grpc_MovieRatingDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022movie_rating.proto\022\rexamples.grpc\032\034goo" +
      "gle/api/annotations.proto\"\007\n\005Empty\"\025\n\007Mo" +
      "vieId\022\n\n\002id\030\001 \001(\t\")\n\014MovieDetails\022\n\n\002id\030" +
      "\001 \001(\t\022\r\n\005title\030\002 \001(\t\"J\n\013MovieRating\022\014\n\002i" +
      "d\030\001 \001(\tH\000\022\017\n\005title\030\002 \001(\tH\000\022\016\n\006rating\030\003 \001" +
      "(\005B\014\n\ntest_oneof\"0\n\022MovieRatingDetails\022\n" +
      "\n\002id\030\001 \001(\t\022\016\n\006rating\030\002 \001(\0052\357\001\n\023MovieRati" +
      "ngDatabase\022H\n\017GetMovieDetails\022\026.examples" +
      ".grpc.MovieId\032\033.examples.grpc.MovieDetai" +
      "ls\"\000\022?\n\tRateMovie\022\032.examples.grpc.MovieR" +
      "ating\032\024.examples.grpc.Empty\"\000\022M\n\016GetMovi" +
      "eRating\022\026.examples.grpc.MovieId\032!.exampl" +
      "es.grpc.MovieRatingDetails\"\000B$\n com.juli" +
      "enviet.demos.movieratingP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_examples_grpc_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_examples_grpc_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_examples_grpc_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_examples_grpc_MovieId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_examples_grpc_MovieId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_examples_grpc_MovieId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_examples_grpc_MovieDetails_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_examples_grpc_MovieDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_examples_grpc_MovieDetails_descriptor,
        new java.lang.String[] { "Id", "Title", });
    internal_static_examples_grpc_MovieRating_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_examples_grpc_MovieRating_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_examples_grpc_MovieRating_descriptor,
        new java.lang.String[] { "Id", "Title", "Rating", "TestOneof", });
    internal_static_examples_grpc_MovieRatingDetails_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_examples_grpc_MovieRatingDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_examples_grpc_MovieRatingDetails_descriptor,
        new java.lang.String[] { "Id", "Rating", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
