// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: movie_rating.proto
// Protobuf Java Version: 4.29.3

package com.julienviet.demos.movierating;

public interface MovieRatingDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:examples.grpc.MovieRatingDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int32 rating = 2;</code>
   * @return The rating.
   */
  int getRating();
}
