// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: movie_rating.proto
// Protobuf Java Version: 4.29.3

package com.julienviet.demos.movierating;

/**
 * Protobuf type {@code examples.grpc.MovieRating}
 */
public final class MovieRating extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:examples.grpc.MovieRating)
    MovieRatingOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      MovieRating.class.getName());
  }
  // Use MovieRating.newBuilder() to construct.
  private MovieRating(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MovieRating() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.julienviet.demos.movierating.MovieRatingOuterClass.internal_static_examples_grpc_MovieRating_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.julienviet.demos.movierating.MovieRatingOuterClass.internal_static_examples_grpc_MovieRating_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.julienviet.demos.movierating.MovieRating.class, com.julienviet.demos.movierating.MovieRating.Builder.class);
  }

  private int testOneofCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object testOneof_;
  public enum TestOneofCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ID(1),
    TITLE(2),
    TESTONEOF_NOT_SET(0);
    private final int value;
    private TestOneofCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TestOneofCase valueOf(int value) {
      return forNumber(value);
    }

    public static TestOneofCase forNumber(int value) {
      switch (value) {
        case 1: return ID;
        case 2: return TITLE;
        case 0: return TESTONEOF_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public TestOneofCase
  getTestOneofCase() {
    return TestOneofCase.forNumber(
        testOneofCase_);
  }

  public static final int ID_FIELD_NUMBER = 1;
  /**
   * <code>string id = 1;</code>
   * @return Whether the id field is set.
   */
  public boolean hasId() {
    return testOneofCase_ == 1;
  }
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  public java.lang.String getId() {
    java.lang.Object ref = "";
    if (testOneofCase_ == 1) {
      ref = testOneof_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (testOneofCase_ == 1) {
        testOneof_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = "";
    if (testOneofCase_ == 1) {
      ref = testOneof_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (testOneofCase_ == 1) {
        testOneof_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  /**
   * <code>string title = 2;</code>
   * @return Whether the title field is set.
   */
  public boolean hasTitle() {
    return testOneofCase_ == 2;
  }
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = "";
    if (testOneofCase_ == 2) {
      ref = testOneof_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (testOneofCase_ == 2) {
        testOneof_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = "";
    if (testOneofCase_ == 2) {
      ref = testOneof_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (testOneofCase_ == 2) {
        testOneof_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RATING_FIELD_NUMBER = 3;
  private int rating_ = 0;
  /**
   * <code>int32 rating = 3;</code>
   * @return The rating.
   */
  @java.lang.Override
  public int getRating() {
    return rating_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (testOneofCase_ == 1) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, testOneof_);
    }
    if (testOneofCase_ == 2) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, testOneof_);
    }
    if (rating_ != 0) {
      output.writeInt32(3, rating_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (testOneofCase_ == 1) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, testOneof_);
    }
    if (testOneofCase_ == 2) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, testOneof_);
    }
    if (rating_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, rating_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.julienviet.demos.movierating.MovieRating)) {
      return super.equals(obj);
    }
    com.julienviet.demos.movierating.MovieRating other = (com.julienviet.demos.movierating.MovieRating) obj;

    if (getRating()
        != other.getRating()) return false;
    if (!getTestOneofCase().equals(other.getTestOneofCase())) return false;
    switch (testOneofCase_) {
      case 1:
        if (!getId()
            .equals(other.getId())) return false;
        break;
      case 2:
        if (!getTitle()
            .equals(other.getTitle())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RATING_FIELD_NUMBER;
    hash = (53 * hash) + getRating();
    switch (testOneofCase_) {
      case 1:
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
        break;
      case 2:
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.julienviet.demos.movierating.MovieRating parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.julienviet.demos.movierating.MovieRating parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.julienviet.demos.movierating.MovieRating parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.julienviet.demos.movierating.MovieRating parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.julienviet.demos.movierating.MovieRating parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.julienviet.demos.movierating.MovieRating parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.julienviet.demos.movierating.MovieRating parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.julienviet.demos.movierating.MovieRating parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.julienviet.demos.movierating.MovieRating parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.julienviet.demos.movierating.MovieRating parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.julienviet.demos.movierating.MovieRating parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.julienviet.demos.movierating.MovieRating parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.julienviet.demos.movierating.MovieRating prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code examples.grpc.MovieRating}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:examples.grpc.MovieRating)
      com.julienviet.demos.movierating.MovieRatingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.julienviet.demos.movierating.MovieRatingOuterClass.internal_static_examples_grpc_MovieRating_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.julienviet.demos.movierating.MovieRatingOuterClass.internal_static_examples_grpc_MovieRating_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.julienviet.demos.movierating.MovieRating.class, com.julienviet.demos.movierating.MovieRating.Builder.class);
    }

    // Construct using com.julienviet.demos.movierating.MovieRating.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rating_ = 0;
      testOneofCase_ = 0;
      testOneof_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.julienviet.demos.movierating.MovieRatingOuterClass.internal_static_examples_grpc_MovieRating_descriptor;
    }

    @java.lang.Override
    public com.julienviet.demos.movierating.MovieRating getDefaultInstanceForType() {
      return com.julienviet.demos.movierating.MovieRating.getDefaultInstance();
    }

    @java.lang.Override
    public com.julienviet.demos.movierating.MovieRating build() {
      com.julienviet.demos.movierating.MovieRating result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.julienviet.demos.movierating.MovieRating buildPartial() {
      com.julienviet.demos.movierating.MovieRating result = new com.julienviet.demos.movierating.MovieRating(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.julienviet.demos.movierating.MovieRating result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rating_ = rating_;
      }
    }

    private void buildPartialOneofs(com.julienviet.demos.movierating.MovieRating result) {
      result.testOneofCase_ = testOneofCase_;
      result.testOneof_ = this.testOneof_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.julienviet.demos.movierating.MovieRating) {
        return mergeFrom((com.julienviet.demos.movierating.MovieRating)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.julienviet.demos.movierating.MovieRating other) {
      if (other == com.julienviet.demos.movierating.MovieRating.getDefaultInstance()) return this;
      if (other.getRating() != 0) {
        setRating(other.getRating());
      }
      switch (other.getTestOneofCase()) {
        case ID: {
          testOneofCase_ = 1;
          testOneof_ = other.testOneof_;
          onChanged();
          break;
        }
        case TITLE: {
          testOneofCase_ = 2;
          testOneof_ = other.testOneof_;
          onChanged();
          break;
        }
        case TESTONEOF_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              testOneofCase_ = 1;
              testOneof_ = s;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              testOneofCase_ = 2;
              testOneof_ = s;
              break;
            } // case 18
            case 24: {
              rating_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int testOneofCase_ = 0;
    private java.lang.Object testOneof_;
    public TestOneofCase
        getTestOneofCase() {
      return TestOneofCase.forNumber(
          testOneofCase_);
    }

    public Builder clearTestOneof() {
      testOneofCase_ = 0;
      testOneof_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>string id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return testOneofCase_ == 1;
    }
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 1) {
        ref = testOneof_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (testOneofCase_ == 1) {
          testOneof_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 1) {
        ref = testOneof_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (testOneofCase_ == 1) {
          testOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      testOneofCase_ = 1;
      testOneof_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      if (testOneofCase_ == 1) {
        testOneofCase_ = 0;
        testOneof_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      testOneofCase_ = 1;
      testOneof_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string title = 2;</code>
     * @return Whether the title field is set.
     */
    @java.lang.Override
    public boolean hasTitle() {
      return testOneofCase_ == 2;
    }
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 2) {
        ref = testOneof_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (testOneofCase_ == 2) {
          testOneof_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 2) {
        ref = testOneof_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (testOneofCase_ == 2) {
          testOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      testOneofCase_ = 2;
      testOneof_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      if (testOneofCase_ == 2) {
        testOneofCase_ = 0;
        testOneof_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      testOneofCase_ = 2;
      testOneof_ = value;
      onChanged();
      return this;
    }

    private int rating_ ;
    /**
     * <code>int32 rating = 3;</code>
     * @return The rating.
     */
    @java.lang.Override
    public int getRating() {
      return rating_;
    }
    /**
     * <code>int32 rating = 3;</code>
     * @param value The rating to set.
     * @return This builder for chaining.
     */
    public Builder setRating(int value) {

      rating_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rating = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRating() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rating_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:examples.grpc.MovieRating)
  }

  // @@protoc_insertion_point(class_scope:examples.grpc.MovieRating)
  private static final com.julienviet.demos.movierating.MovieRating DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.julienviet.demos.movierating.MovieRating();
  }

  public static com.julienviet.demos.movierating.MovieRating getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MovieRating>
      PARSER = new com.google.protobuf.AbstractParser<MovieRating>() {
    @java.lang.Override
    public MovieRating parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MovieRating> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MovieRating> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.julienviet.demos.movierating.MovieRating getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

