// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: movie_rating.proto
// Protobuf Java Version: 4.29.3

package examples.movie_rating;

public interface MovieIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:examples.grpc.MovieId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
